--liquibase formatted sql

--changeset JAIDEEP:2
CREATE TABLE TITLE (
    ID SERIAL PRIMARY KEY,
    ORIGINAL VARCHAR(200) NOT NULL,
    ENGLISH_TRANSLATION VARCHAR(200) NOT NULL,
    ENGLISH_TRANSLITERATION VARCHAR(200) NOT NULL
);

-- drop table TITLE;