--liquibase formatted sql

--changeset JAIDEEP:3
CREATE TABLE SONG (
    ID SERIAL PRIMARY KEY,
    SHOW_ON_LANDING_PAGE BOOLEAN,
    CATEGORY VARCHAR(200) NOT NULL,
    DURATION VARCHAR(200),
    YOUTUBE_VIDEO_ID varchar(200) NOT NULL,
    THUMBNAIL_URL varchar(200),
    ORIGINAL_TITLE VARCHAR(200) NOT NULL,
    ENGLISH_TRANSLATION VARCHAR(200) NOT NULL,
    ENGLISH_TRANSLITERATION VARCHAR(200) NOT NULL
);

-- drop table SONG;