--liquibase formatted sql

--changeset PADMA:4
CREATE TABLE WORD (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    SYNONYM VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(100) NOT NULL,
    SHOW_ON_LANDING_PAGE VARCHAR(10) NOT NULL
);

--rollback drop table WORD;