--liquibase formatted sql

--changeset JAIDEEP:4
CREATE TABLE WORD (
    ID SERIAL,
    NAME VARCHAR(100) NOT NULL,
    SYNONYM VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(100) NOT NULL,
    MEANING VARCHAR(300) NOT NULL,
    SHOWONLANDINGPAGE VARCHAR(10) NOT NULL
);