--liquibase formatted sql

--changeset PADMA:5
CREATE TABLE COUPLET (
    ID SERIAL,
    DESCRIPTION VARCHAR(200) NOT NULL,
    CATEGORY VARCHAR(100) NOT NULL,
    SHOW_ON_LANDINGPAGE VARCHAR(10) NOT NULL
);