--liquibase formatted sql

--changeset JAIDEEP:15
ALTER TABLE SONG ADD COLUMN MEDIA_CATEGORY INT REFERENCES CATEGORY(ID);
ALTER TABLE SONG RENAME COLUMN CATEGORY_ID TO SONG_CATEGORY;

--rollback ALTER TABLE CATEGORY DROP COLUMN MEDIA_CATEGORY;
--rollback ALTER TABLE CATEGORY RENAME COLUMN SONG_CATEGORY TO CATEGORY_ID;