--liquibase formatted sql

--changeset PADMA:3
CREATE TABLE SONG (
    ID SERIAL PRIMARY KEY,
    SHOW_ON_LANDING_PAGE BOOLEAN,
    DURATION VARCHAR(200),
    YOUTUBE_VIDEO_ID varchar(20) NOT NULL,
    THUMBNAIL_URL varchar(200),
    ORIGINAL_TITLE VARCHAR(200) NOT NULL,
    ENGLISH_TRANSLATION VARCHAR(200) NOT NULL,
    ENGLISH_TRANSLITERATION VARCHAR(200) NOT NULL,
    CATEGORY_ID INT REFERENCES CATEGORY(ID)
);

--rollback drop table SONG;