--liquibase formatted sql

--changeset PADMA:5
CREATE TABLE COUPLET (
    ID SERIAL PRIMARY KEY,
    ORIGINAL_TITLE VARCHAR(200) NOT NULL,
    ENGLISH_TRANSLATION VARCHAR(200) NOT NULL,
    ENGLISH_TRANSLITERATION VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(200) NOT NULL,
    SHOW_ON_LANDING_PAGE BOOLEAN NOT NULL,
    CATEGORY_ID INT REFERENCES CATEGORY(ID),
    POET_ID INT REFERENCES PERSON(ID)
);

--rollback drop table COUPLET;