--liquibase formatted sql

--changeset JAIDEEP:12
CREATE TABLE COUPLET_GENRE (
    ID SERIAL,
    COUPLET_ID INT FOREIGN KEY, 
    GENRE_ID INT FOREIGN KEY,
    CONSTRAINT COUPLET_AND_GENRE UNIQUE(COUPLET_ID, GENRE_ID)
);

--rollback drop table COUPLET_GENRE;