--liquibase formatted sql

--changeset PADMA:24
UPDATE SONG SET IS_AUTHORING_COMPLETE = true where YOUTUBE_VIDEO_ID = 'tNh2kjmSzPw';
UPDATE SONG SET IS_AUTHORING_COMPLETE = true where YOUTUBE_VIDEO_ID = '7Gg0vSOZhJQ';
UPDATE SONG SET IS_AUTHORING_COMPLETE = true where YOUTUBE_VIDEO_ID = 'J4IU5tDlD_s';