--liquibase formatted sql

--changeset PADMA:35
ALTER TABLE UMBRELLA_TITLE RENAME TO TITLE;
ALTER TABLE TITLE ADD COLUMN CATEGORY_ID INT REFERENCES CATEGORY(ID);
ALTER TABLE TITLE RENAME COLUMN TITLE TO ORIGINAL_TITLE;