--liquibase formatted sql

--changeset PADMA:37
ALTER TABLE SONG DROP COLUMN ORIGINAL_TITLE;
ALTER TABLE SONG DROP COLUMN ENGLISH_TRANSLATION;
ALTER TABLE SONG DROP COLUMN ENGLISH_TRANSLITERATION;
ALTER TABLE SONG ADD COLUMN SONG_TITLE_ID INT REFERENCES TITLE(ID);
