--liquibase formatted sql

--changeset PADMA:40
ALTER TABLE COUPLET DROP COLUMN DESCRIPTION;
ALTER TABLE COUPLET ADD COLUMN ORIGINAL_TEXT VARCHAR(500);
ALTER TABLE COUPLET ADD COLUMN ENGLISH_TRANSLATION_TEXT VARCHAR(500);
ALTER TABLE COUPLET ADD COLUMN ENGLISH_TRANSLITERATION_TEXT VARCHAR(500);