--liquibase formatted sql 

--changeset JAIDEEP:57

CREATE TABLE SONG_WORD (
	ID SERIAL NOT NULL,
	SONG_ID INT,
	WORD_ID INT,
	CONSTRAINT WORD_ID_FKEY FOREIGN KEY (WORD_ID) REFERENCES WORD(ID) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE SET NULL,
	CONSTRAINT SONG_ID_FKEY FOREIGN KEY (SONG_ID) REFERENCES SONG(ID) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE SET NULL
);