--liquibase formatted sql

--changeset JAIDEEP:1
CREATE TABLE COUPLET (
    ID SERIAL FOREIGN KEY,
    TITLE_IN_HINDI VARCHAR(255) NOT NULL,
    TITLE_IN_ENGLISH_TRANSLATION VARCHAR(255) NOT NULL,
    TITLE_IN_ENGLISH_TRANSLITERATION VARCHAR(255) NOT NULL,
    LANGUAGE VARCHAR(200),
    COUPLET_TEXT_IN_HINDI VARCHAR(400) NOT NULL,
    COUPLET_TEXT_IN_ENGLISH_TRANSLITERATION VARCHAR(400) NOT NULL,
    COUPLET_AUDIO_FILE_URL VARCHAR(300) NOT NULL,
    DISPLAY_ON_HOME_DASHBOARD BOOLEAN.
    PERSON_ID INT FOREIGN KEY,

);
--rollback drop table test1;

--changeset JAIDEEP:2 dbms:postgresql
create sequence seq_test;