--liquibase formatted sql

--changeset JAIDEEp:20
UPDATE SONG SET MEDIA_CATEGORY = 4 where YOUTUBE_VIDEO_ID = 'tNh2kjmSzPw';
UPDATE SONG SET MEDIA_CATEGORY= 3 where YOUTUBE_VIDEO_ID = '7Gg0vSOZhJQ';
UPDATE SONG SET MEDIA_CATEGORY= 4 where YOUTUBE_VIDEO_ID = 'J4IU5tDlD_s';