INSERT INTO SONG(
    TITLE_ID ,
    SINGER_ID ,
    POET_ID ,
    SHOW_ON_LANDING_PAGE,
    CATEGORY,
    DURATION,
    YOUTUBE_VIDEO_ID
)
VALUES
(5,3,4,TRUE,'SONG','5:45','tNh2kjmSzPw'),
(6,5,6,TRUE,'SONG','5:10','7Gg0vSOZhJQ'),
(7,7,8,TRUE,'SONG','7:05','J4IU5tDlD_s');
