--changeset JAIDEEP:8
CREATE TABLE COUPLET_LANGUAGE (
    ID SERIAL,
    COUPLET_ID INT FOREIGN KEY, 
    LANGUAGE_ID INT FOREIGN KEY,
    CONSTRAINT COUPLET_AND_LANGAUGE UNIQUE(COUPLET_ID, LANGUAGE_ID)
);

--rollback drop table COUPLET_LANGUAGE;