--changeset JAIDEEP:11
CREATE TABLE COUPLET_AND_COUPLET_STRING (
    ID SERIAL,
    COUPLET_ID INT references COUPLET(ID),
    COUPLET_STRING_ID INT references COUPLET_STRING(ID),
    CONSTRAINT COUPLET_AND_COUPLET_AND_STRING UNIQUE(COUPLET_ID, COUPLET_STRING_ID)
);

--rollback drop table COUPLET_AND_COUPLET_STRING;