CREATE TABLE SONG(
	ID SERIAL PRIMARY KEY,
	TITLE VARCHAR(30) NOT NULL,
	SINGER VARCHAR(30),
	POET VARCHAR(30),
	INFORMATION VARCHAR(100), 
	UMBRELLA_SONG VARCHAR(30),
	SOUNDCLOUD_AUDIO_URL VARCHAR(50),
	THUMBNAIL_URL VARCHAR(50)
);