CREATE TABLE REFLECTION_DETAILS(
	ID SERIAL PRIMARY KEY,
	TITLE VARCHAR(30) NOT NULL,
	SONG VARCHAR(30),
	TRANSLATION VARCHAR(30),
	TRANSCRIPT VARCHAR(30),
	TAGS VARCHAR(20),
	POET VARCHAR(30),
	AUTHOR VARCHAR(30),
	LOCATION VARCHAR(50),
	EVENT VARCHAR(30),
	THUMBNAILS_URL VARCHAR(30)
);
