CREATE TABLE WORD_DETAILS(
	ID SERIAL PRIMARY KEY,
	WORD VARCHAR(30),
	TRANSLATION VARCHAR(30),
	TRANSLITERATION VARCHAR(30),
	LITERAL_MEANING VARCHAR(60),
	MEANING_IN_THE_CONTEXT VARCHAR(60),
	SYNONYMS VARCHAR(70),
	WORD_SUMMARY VARCHAR(80),
	DETAILED_WORD_WRITE_UP VARCHAR(100)
);